spring:
  application:
    name: tech-challenge-f4-ms-produto
  datasource:
    hikari:
      pool-name: tech-challenge-f4-ms-produto
      maximum-pool-size: 5
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-produto
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  cloud:
    function:
      web:
        path: /api

load:
  input-path: C:\Users\Gabriel\Downloads\loadProducts

server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    br:
      com:
        pupposoft:
          poc:
            cloudstream: TRACE
