spring:
  application:
    name: tc-f4-ms-product-catalog
  datasource:
    hikari:
      pool-name: tc-f4-ms-product-catalog
      maximum-pool-size: 5
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-product
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  cloud:
    function:
      web:
        path: /api

load:
  input-path: ${USERPROFILE}\Downloads\loadProducts

server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    br:
      com:
        pupposoft:
          poc:
            cloudstream: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instanceId: ${spring.application.name}